## TicTacToe

In [24]:
import numpy as np
from __future__ import print_function

In [304]:
empty = 0
x = 1
oh = -1
init_board = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]])
print(board)
UNEXPLORED=0

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [305]:
class Node:
    def __init__(self, board, depth):
        self.board = board
        self.prob = 0.5
        self.children = {}   # key = (player, (x,y)) , value = node
        self.depth = depth
        
    def __repr__(self):
        return '\n'+ '\t'*self.depth + str(self.board).replace('\n', '\n'+'\t'*self.depth) +" "+str(self.prob)+' '+str(self.children.values())

root = Node(init_board, 0) 
print(root)


[[0 0 0]
 [0 0 0]
 [0 0 0]] 0.5 []


In [306]:
def expand(node, position, player):
    if node.board[position] != 0:
        key = (node.board[position], position)
        return None
    key = (player, position)
    new_board = np.copy(node.board)
    new_board[position] = player
    new_child = Node(new_board, node.depth+1)
    node.children[key] = new_child
    return new_child

In [307]:
expand(root,(0,0),x)
select = expand(root,(1,1),oh)
expand(select, (2,2),x)
expand(select, (2,2),oh)
expand(select, (1,1),x)
print(root)



[[0 0 0]
 [0 0 0]
 [0 0 0]] 0.5 [
	[[1 0 0]
	 [0 0 0]
	 [0 0 0]] 0.5 [], 
	[[ 0  0  0]
	 [ 0 -1  0]
	 [ 0  0  0]] 0.5 [
		[[ 0  0  0]
		 [ 0 -1  0]
		 [ 0  0 -1]] 0.5 [], 
		[[ 0  0  0]
		 [ 0 -1  0]
		 [ 0  0  1]] 0.5 []]]


In [308]:
board = root.board
rows = len(board)
cols = len(board[0])
def Winner(board):
    for i in range(0,rows):
        row = board[i,:]
        if sum(row) == x*cols:
            return x
        elif sum(row) == oh*cols:
            return oh
    for j in range(0, cols):
        col = board[:,j]
        if sum(col) == x*rows:
            return x
        elif sum(col) == oh*rows:
            return oh
    diag_right = board.diagonal()
    diag_left = board[:, ::-1].diagonal()
    if sum(diag_right) == x*rows:
        return x
    if sum(diag_left) == x*rows:
        return x
    if sum(diag_right) == oh*rows:
        return oh
    if sum(diag_left) == oh*rows:
        return oh
    return 0
print(Winner(np.array([[x,x,x], [0,0,0], [0,oh,oh]])))
print(Winner(np.array([[x,oh,0], [x,0,0], [x,oh,oh]])))
print(Winner(np.array([[x,oh,0], [x,oh,0], [oh,oh,0]])))
print(Winner(np.array([[x,oh,0], [x,x,0], [oh,oh,x]])))
print(Winner(np.array([[x,oh,oh], [x,oh,0], [oh,0,0]])))
print(Winner(init_board))


1
1
-1
1
-1
0


In [321]:
def solve(root, next_player):
    winner = Winner(root.board)
    if winner != 0:
        root.prob = 0.0 if winner == oh else 1.0
        return
    root.prob = 0.0
    for i in range(len(board)):
        for j in range(len(board[0])):
            expand(root, (i,j), next_player)
    if len(root.children) == 0:
        return
    for child in root.children.values():
        solve(child, next_player * -1)
        root.prob += child.prob
    root.prob /= len(root.children)

root = Node(init_board, 0)
solve(root, x)

In [310]:
def play_x(node):
    return max(node.children.values(), key= lambda x: x.prob)
def play_oh(node):
    return min(node.children.values(), key= lambda x: x.prob)
play_x(play_x(play_x(root).children.values()[0]).children.values()[0])


					[[ 1  1  1]
					 [-1 -1  0]
					 [ 0  0  0]] 1.0 []

# Play TicTacToe Against the Computer

In [360]:
node = root
print(repr(node.board))

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])


### The computer's move:

In [368]:
node = play_oh(node)
print(repr(node.board))

array([[ 1, -1,  1],
       [ 0, -1, -1],
       [-1,  1,  1]])


### Your move:

In [369]:
node = node.children[(1,(1,0))]
print(repr(node.board))

array([[ 1, -1,  1],
       [ 1, -1, -1],
       [-1,  1,  1]])
